// Decompiled with JetBrains decompiler
// Type: CrazyStorm_1._03.TimeEvent
// Assembly: CrazyStorm 1.03, Version=1.0.0.3, Culture=neutral, PublicKeyToken=null
// MVID: 84431CDC-1E34-49EF-A5C5-D546FEF5A655
// Assembly location: E:\CrazyStorm 1.03I\CrazyStorm 1.03.exe

using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace CrazyStorm_1._03
{
  public class TimeEvent : Form
  { 
    private GroupBox GroupBox1;
    private Label label1;
    public CheckBox 跳转启用;
    public TextBox 跳转执行次数;
    private GroupBox groupBox2;
    public TextBox 跳转条件值;
    public RadioButton 小于1;
    public RadioButton 等于1;
    public RadioButton 大于1;
    public ComboBox 跳转条件;
    private GroupBox groupBox3;
    private GroupBox groupBox4;
    public TextBox 震屏条件值;
    public RadioButton 小于2;
    public RadioButton 等于2;
    public RadioButton 大于2;
    public ComboBox 震屏条件;
    public TextBox 震屏持续时间;
    private Label label2;
    public CheckBox 震屏启用;
    private GroupBox groupBox5;
    private GroupBox groupBox6;
    public TextBox 停滞条件值;
    public RadioButton 小于3;
    public RadioButton 等于3;
    public RadioButton 大于3;
    public ComboBox 停滞条件;
    private Label label3;
    public CheckBox 停滞启用;
    public ComboBox 停滞程度;
    public TextBox 停滞时间;
    private Label label4;
    public TextBox 跳转目标;
    private Label label5;
    public TextBox 震屏强度;
    private Label label6;
    public GlobalEvent GE;
    public int id;
         
    private void InitializeComponent()
    {
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (TimeEvent));
      this.GroupBox1 = new GroupBox();
      this.跳转目标 = new TextBox();
      this.label5 = new Label();
      this.groupBox2 = new GroupBox();
      this.跳转条件值 = new TextBox();
      this.小于1 = new RadioButton();
      this.等于1 = new RadioButton();
      this.大于1 = new RadioButton();
      this.跳转条件 = new ComboBox();
      this.跳转执行次数 = new TextBox();
      this.label1 = new Label();
      this.跳转启用 = new CheckBox();
      this.groupBox3 = new GroupBox();
      this.震屏强度 = new TextBox();
      this.label6 = new Label();
      this.groupBox4 = new GroupBox();
      this.震屏条件值 = new TextBox();
      this.小于2 = new RadioButton();
      this.等于2 = new RadioButton();
      this.大于2 = new RadioButton();
      this.震屏条件 = new ComboBox();
      this.震屏持续时间 = new TextBox();
      this.label2 = new Label();
      this.震屏启用 = new CheckBox();
      this.groupBox5 = new GroupBox();
      this.停滞时间 = new TextBox();
      this.label4 = new Label();
      this.停滞程度 = new ComboBox();
      this.groupBox6 = new GroupBox();
      this.停滞条件值 = new TextBox();
      this.小于3 = new RadioButton();
      this.等于3 = new RadioButton();
      this.大于3 = new RadioButton();
      this.停滞条件 = new ComboBox();
      this.label3 = new Label();
      this.停滞启用 = new CheckBox();
      this.GroupBox1.SuspendLayout();
      this.groupBox2.SuspendLayout();
      this.groupBox3.SuspendLayout();
      this.groupBox4.SuspendLayout();
      this.groupBox5.SuspendLayout();
      this.groupBox6.SuspendLayout();
      this.SuspendLayout();
      this.GroupBox1.Controls.Add((Control) this.跳转目标);
      this.GroupBox1.Controls.Add((Control) this.label5);
      this.GroupBox1.Controls.Add((Control) this.groupBox2);
      this.GroupBox1.Controls.Add((Control) this.跳转执行次数);
      this.GroupBox1.Controls.Add((Control) this.label1);
      this.GroupBox1.Controls.Add((Control) this.跳转启用);
      this.GroupBox1.Location = new Point(2, 12);
      this.GroupBox1.Name = "GroupBox1";
      this.GroupBox1.Size = new Size(269, 108);
      this.GroupBox1.TabIndex = 0;
      this.GroupBox1.TabStop = false;
      this.GroupBox1.Text = "跳转";
      this.跳转目标.Location = new Point(112, 79);
      this.跳转目标.Name = "跳转目标";
      this.跳转目标.Size = new Size(50, 21);
      this.跳转目标.TabIndex = 36;
      this.跳转目标.TextAlign = HorizontalAlignment.Center;
      this.label5.AutoSize = true;
      this.label5.Location = new Point(75, 82);
      this.label5.Name = "label5";
      this.label5.Size = new Size(29, 12);
      this.label5.TabIndex = 37;
      this.label5.Text = "目标";
      this.groupBox2.Controls.Add((Control) this.跳转条件值);
      this.groupBox2.Controls.Add((Control) this.小于1);
      this.groupBox2.Controls.Add((Control) this.等于1);
      this.groupBox2.Controls.Add((Control) this.大于1);
      this.groupBox2.Controls.Add((Control) this.跳转条件);
      this.groupBox2.Location = new Point(6, 20);
      this.groupBox2.Name = "groupBox2";
      this.groupBox2.Size = new Size(257, 50);
      this.groupBox2.TabIndex = 35;
      this.groupBox2.TabStop = false;
      this.groupBox2.Text = "附加条件（可省略）";
      this.跳转条件值.Location = new Point(197, 18);
      this.跳转条件值.Name = "跳转条件值";
      this.跳转条件值.Size = new Size(50, 21);
      this.跳转条件值.TabIndex = 39;
      this.跳转条件值.TextAlign = HorizontalAlignment.Center;
      this.小于1.AutoSize = true;
      this.小于1.Cursor = Cursors.Default;
      this.小于1.Location = new Point(162, 20);
      this.小于1.Name = "小于1";
      this.小于1.Size = new Size(29, 16);
      this.小于1.TabIndex = 38;
      this.小于1.Text = "<";
      this.小于1.UseVisualStyleBackColor = true;
      this.等于1.AutoSize = true;
      this.等于1.Checked = true;
      this.等于1.Location = new Point((int) sbyte.MaxValue, 20);
      this.等于1.Name = "等于1";
      this.等于1.Size = new Size(29, 16);
      this.等于1.TabIndex = 37;
      this.等于1.TabStop = true;
      this.等于1.Text = "=";
      this.等于1.UseVisualStyleBackColor = true;
      this.大于1.AutoSize = true;
      this.大于1.Location = new Point(93, 20);
      this.大于1.Name = "大于1";
      this.大于1.Size = new Size(29, 16);
      this.大于1.TabIndex = 36;
      this.大于1.Text = ">";
      this.大于1.UseVisualStyleBackColor = true;
      this.跳转条件.DropDownStyle = ComboBoxStyle.DropDownList;
      this.跳转条件.FormattingEnabled = true;
      this.跳转条件.Location = new Point(10, 19);
      this.跳转条件.Name = "跳转条件";
      this.跳转条件.Size = new Size(76, 20);
      this.跳转条件.TabIndex = 35;
      this.跳转执行次数.Location = new Point(203, 79);
      this.跳转执行次数.Name = "跳转执行次数";
      this.跳转执行次数.Size = new Size(50, 21);
      this.跳转执行次数.TabIndex = 1;
      this.跳转执行次数.TextAlign = HorizontalAlignment.Center;
      this.label1.AutoSize = true;
      this.label1.Location = new Point(166, 82);
      this.label1.Name = "label1";
      this.label1.Size = new Size(29, 12);
      this.label1.TabIndex = 2;
      this.label1.Text = "次数";
      this.跳转启用.AutoSize = true;
      this.跳转启用.Location = new Point(16, 81);
      this.跳转启用.Name = "跳转启用";
      this.跳转启用.Size = new Size(48, 16);
      this.跳转启用.TabIndex = 1;
      this.跳转启用.Text = "启用";
      this.跳转启用.UseVisualStyleBackColor = true;
      this.groupBox3.Controls.Add((Control) this.震屏强度);
      this.groupBox3.Controls.Add((Control) this.label6);
      this.groupBox3.Controls.Add((Control) this.groupBox4);
      this.groupBox3.Controls.Add((Control) this.震屏持续时间);
      this.groupBox3.Controls.Add((Control) this.label2);
      this.groupBox3.Controls.Add((Control) this.震屏启用);
      this.groupBox3.Location = new Point(2, 126);
      this.groupBox3.Name = "groupBox3";
      this.groupBox3.Size = new Size(269, 108);
      this.groupBox3.TabIndex = 36;
      this.groupBox3.TabStop = false;
      this.groupBox3.Text = "震屏";
      this.震屏强度.Location = new Point(110, 79);
      this.震屏强度.Name = "震屏强度";
      this.震屏强度.Size = new Size(50, 21);
      this.震屏强度.TabIndex = 36;
      this.震屏强度.TextAlign = HorizontalAlignment.Center;
      this.label6.AutoSize = true;
      this.label6.Location = new Point(73, 82);
      this.label6.Name = "label6";
      this.label6.Size = new Size(29, 12);
      this.label6.TabIndex = 37;
      this.label6.Text = "强度";
      this.groupBox4.Controls.Add((Control) this.震屏条件值);
      this.groupBox4.Controls.Add((Control) this.小于2);
      this.groupBox4.Controls.Add((Control) this.等于2);
      this.groupBox4.Controls.Add((Control) this.大于2);
      this.groupBox4.Controls.Add((Control) this.震屏条件);
      this.groupBox4.Location = new Point(6, 20);
      this.groupBox4.Name = "groupBox4";
      this.groupBox4.Size = new Size(257, 50);
      this.groupBox4.TabIndex = 35;
      this.groupBox4.TabStop = false;
      this.groupBox4.Text = "附加条件（可省略）";
      this.震屏条件值.Location = new Point(197, 18);
      this.震屏条件值.Name = "震屏条件值";
      this.震屏条件值.Size = new Size(50, 21);
      this.震屏条件值.TabIndex = 39;
      this.震屏条件值.TextAlign = HorizontalAlignment.Center;
      this.小于2.AutoSize = true;
      this.小于2.Cursor = Cursors.Default;
      this.小于2.Location = new Point(162, 20);
      this.小于2.Name = "小于2";
      this.小于2.Size = new Size(29, 16);
      this.小于2.TabIndex = 38;
      this.小于2.Text = "<";
      this.小于2.UseVisualStyleBackColor = true;
      this.等于2.AutoSize = true;
      this.等于2.Checked = true;
      this.等于2.Location = new Point((int) sbyte.MaxValue, 20);
      this.等于2.Name = "等于2";
      this.等于2.Size = new Size(29, 16);
      this.等于2.TabIndex = 37;
      this.等于2.TabStop = true;
      this.等于2.Text = "=";
      this.等于2.UseVisualStyleBackColor = true;
      this.大于2.AutoSize = true;
      this.大于2.Location = new Point(93, 20);
      this.大于2.Name = "大于2";
      this.大于2.Size = new Size(29, 16);
      this.大于2.TabIndex = 36;
      this.大于2.Text = ">";
      this.大于2.UseVisualStyleBackColor = true;
      this.震屏条件.DropDownStyle = ComboBoxStyle.DropDownList;
      this.震屏条件.FormattingEnabled = true;
      this.震屏条件.Location = new Point(10, 19);
      this.震屏条件.Name = "震屏条件";
      this.震屏条件.Size = new Size(76, 20);
      this.震屏条件.TabIndex = 35;
      this.震屏持续时间.Location = new Point(203, 79);
      this.震屏持续时间.Name = "震屏持续时间";
      this.震屏持续时间.Size = new Size(50, 21);
      this.震屏持续时间.TabIndex = 1;
      this.震屏持续时间.TextAlign = HorizontalAlignment.Center;
      this.label2.AutoSize = true;
      this.label2.Location = new Point(166, 82);
      this.label2.Name = "label2";
      this.label2.Size = new Size(29, 12);
      this.label2.TabIndex = 2;
      this.label2.Text = "时间";
      this.震屏启用.AutoSize = true;
      this.震屏启用.Location = new Point(16, 81);
      this.震屏启用.Name = "震屏启用";
      this.震屏启用.Size = new Size(48, 16);
      this.震屏启用.TabIndex = 1;
      this.震屏启用.Text = "启用";
      this.震屏启用.UseVisualStyleBackColor = true;
      this.groupBox5.Controls.Add((Control) this.停滞时间);
      this.groupBox5.Controls.Add((Control) this.label4);
      this.groupBox5.Controls.Add((Control) this.停滞程度);
      this.groupBox5.Controls.Add((Control) this.groupBox6);
      this.groupBox5.Controls.Add((Control) this.label3);
      this.groupBox5.Controls.Add((Control) this.停滞启用);
      this.groupBox5.Location = new Point(2, 240);
      this.groupBox5.Name = "groupBox5";
      this.groupBox5.Size = new Size(269, 108);
      this.groupBox5.TabIndex = 37;
      this.groupBox5.TabStop = false;
      this.groupBox5.Text = "停滞";
      this.停滞时间.Location = new Point(203, 78);
      this.停滞时间.Name = "停滞时间";
      this.停滞时间.Size = new Size(50, 21);
      this.停滞时间.TabIndex = 36;
      this.停滞时间.TextAlign = HorizontalAlignment.Center;
      this.label4.AutoSize = true;
      this.label4.Location = new Point(168, 82);
      this.label4.Name = "label4";
      this.label4.Size = new Size(29, 12);
      this.label4.TabIndex = 37;
      this.label4.Text = "时间";
      this.停滞程度.DropDownStyle = ComboBoxStyle.DropDownList;
      this.停滞程度.FormattingEnabled = true;
      this.停滞程度.Items.AddRange(new object[2]
      {
        (object) "缓慢",
        (object) "完全"
      });
      this.停滞程度.Location = new Point(112, 78);
      this.停滞程度.Name = "停滞程度";
      this.停滞程度.Size = new Size(50, 20);
      this.停滞程度.TabIndex = 40;
      this.groupBox6.Controls.Add((Control) this.停滞条件值);
      this.groupBox6.Controls.Add((Control) this.小于3);
      this.groupBox6.Controls.Add((Control) this.等于3);
      this.groupBox6.Controls.Add((Control) this.大于3);
      this.groupBox6.Controls.Add((Control) this.停滞条件);
      this.groupBox6.Location = new Point(6, 20);
      this.groupBox6.Name = "groupBox6";
      this.groupBox6.Size = new Size(257, 50);
      this.groupBox6.TabIndex = 35;
      this.groupBox6.TabStop = false;
      this.groupBox6.Text = "附加条件（可省略）";
      this.停滞条件值.Location = new Point(197, 18);
      this.停滞条件值.Name = "停滞条件值";
      this.停滞条件值.Size = new Size(50, 21);
      this.停滞条件值.TabIndex = 39;
      this.停滞条件值.TextAlign = HorizontalAlignment.Center;
      this.小于3.AutoSize = true;
      this.小于3.Cursor = Cursors.Default;
      this.小于3.Location = new Point(162, 20);
      this.小于3.Name = "小于3";
      this.小于3.Size = new Size(29, 16);
      this.小于3.TabIndex = 38;
      this.小于3.Text = "<";
      this.小于3.UseVisualStyleBackColor = true;
      this.等于3.AutoSize = true;
      this.等于3.Checked = true;
      this.等于3.Location = new Point((int) sbyte.MaxValue, 20);
      this.等于3.Name = "等于3";
      this.等于3.Size = new Size(29, 16);
      this.等于3.TabIndex = 37;
      this.等于3.TabStop = true;
      this.等于3.Text = "=";
      this.等于3.UseVisualStyleBackColor = true;
      this.大于3.AutoSize = true;
      this.大于3.Location = new Point(93, 20);
      this.大于3.Name = "大于3";
      this.大于3.Size = new Size(29, 16);
      this.大于3.TabIndex = 36;
      this.大于3.Text = ">";
      this.大于3.UseVisualStyleBackColor = true;
      this.停滞条件.DropDownStyle = ComboBoxStyle.DropDownList;
      this.停滞条件.FormattingEnabled = true;
      this.停滞条件.Location = new Point(10, 19);
      this.停滞条件.Name = "停滞条件";
      this.停滞条件.Size = new Size(76, 20);
      this.停滞条件.TabIndex = 35;
      this.label3.AutoSize = true;
      this.label3.Location = new Point(77, 82);
      this.label3.Name = "label3";
      this.label3.Size = new Size(29, 12);
      this.label3.TabIndex = 2;
      this.label3.Text = "程度";
      this.停滞启用.AutoSize = true;
      this.停滞启用.Location = new Point(16, 81);
      this.停滞启用.Name = "停滞启用";
      this.停滞启用.Size = new Size(48, 16);
      this.停滞启用.TabIndex = 1;
      this.停滞启用.Text = "启用";
      this.停滞启用.UseVisualStyleBackColor = true;
      this.AutoScaleDimensions = new SizeF(6f, 12f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(273, 350);
      this.Controls.Add((Control) this.groupBox5);
      this.Controls.Add((Control) this.groupBox3);
      this.Controls.Add((Control) this.GroupBox1);
      this.Icon = (Icon) componentResourceManager.GetObject("$this.Icon");
      this.MaximizeBox = false;
      this.MinimizeBox = false;
      this.Name = nameof (TimeEvent);
      this.ShowInTaskbar = false;
      this.StartPosition = FormStartPosition.CenterScreen;
      this.Text = "全局事件";
      this.TopMost = true;
      this.FormClosed += new FormClosedEventHandler(this.TimeEvent_FormClosed);
      this.GroupBox1.ResumeLayout(false);
      this.GroupBox1.PerformLayout();
      this.groupBox2.ResumeLayout(false);
      this.groupBox2.PerformLayout();
      this.groupBox3.ResumeLayout(false);
      this.groupBox3.PerformLayout();
      this.groupBox4.ResumeLayout(false);
      this.groupBox4.PerformLayout();
      this.groupBox5.ResumeLayout(false);
      this.groupBox5.PerformLayout();
      this.groupBox6.ResumeLayout(false);
      this.groupBox6.PerformLayout();
      this.ResumeLayout(false);
    }

    public TimeEvent()
    {
      this.InitializeComponent();
    }

    private new void Update()
    {
      try
      {
        this.GE.gotocondition = this.跳转条件.SelectedIndex;
        this.GE.gotoopreator = !this.大于1.Checked ? (!this.小于1.Checked ? "=" : "<") : ">";
        this.GE.gotocvalue = int.Parse(this.跳转条件值.Text);
        this.GE.isgoto = this.跳转启用.Checked;
        this.GE.gototime = int.Parse(this.跳转执行次数.Text);
        this.GE.gotowhere = int.Parse(this.跳转目标.Text);
        this.GE.quakecondition = this.震屏条件.SelectedIndex;
        this.GE.quakeopreator = !this.大于2.Checked ? (!this.小于2.Checked ? "=" : "<") : ">";
        this.GE.quakecvalue = int.Parse(this.震屏条件值.Text);
        this.GE.isquake = this.震屏启用.Checked;
        this.GE.quaketime = int.Parse(this.震屏持续时间.Text);
        this.GE.quakelevel = int.Parse(this.震屏强度.Text);
        this.GE.stopcondition = this.停滞条件.SelectedIndex;
        this.GE.stopopreator = !this.大于3.Checked ? (!this.小于3.Checked ? "=" : "<") : ">";
        this.GE.stopcvalue = int.Parse(this.停滞条件值.Text);
        this.GE.isstop = this.停滞启用.Checked;
        this.GE.stoptime = int.Parse(this.停滞时间.Text);
        this.GE.stoplevel = this.停滞程度.SelectedIndex;
        Time.GE[this.id] = this.GE;
        if (this.跳转条件.SelectedIndex == -1 & this.跳转条件值.Text == "0" & this.跳转执行次数.Text == "0" & this.跳转目标.Text == "0" & this.震屏条件.SelectedIndex == -1 & this.震屏条件值.Text == "0" & this.震屏持续时间.Text == "0" & this.震屏强度.Text == "0" & this.停滞条件.SelectedIndex == -1 & this.停滞条件值.Text == "0" & this.停滞时间.Text == "0" & this.停滞程度.SelectedIndex == -1 || Time.GEcount.Contains(this.id))
          return;
        Time.GEcount.Add(this.id);
      }
      catch  
      {
      }
    }

    private void TimeEvent_FormClosed(object sender, FormClosedEventArgs e)
    {
      this.Update();
    }
  }
}
